#!/usr/bin/env python3

"""
Comprehensive Viral Capsid Contact Analysis

This script performs a comprehensive analysis of residue-residue contacts
within a viral capsid using the output generated by ChimeraX during crystal contacts calculation.
It parses residue contact information, buried solvent-accessible
surface area (SASA), and asymmetric-unit pairing data from the CONTACT
output file.

The script performs the following analyses:
- Parses residue contacts and buried area information.
- Removes duplicate residue pairs and filters unrealistic contacts below
  a user-defined distance threshold.
- Classifies interactions into hydrogen bonds, electrostatic, hydrophobic,
  aromatic, or other interaction types based on residue chemistry and
  inter-residue distance.
- Calculates interaction frequencies between protein chains.
- Determines residue frequencies within protein interfaces.
- Computes distance statistics for all interface contacts.
- Summarizes buried SASA by residue type, chain, and residue chemistry
  class.

The script automatically generates:
- CSV tables containing all processed datasets and summary statistics.
- Figures including:
    • Chain interaction matrix
    • Contact distance distribution
    • Interaction type distribution
    • Residue frequency in interfaces
    • Buried area by residue type
    • Buried area by chain
    • Buried area by residue chemistry
- A text summary describing the analysis and generated outputs.

"""

import argparse
import re
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt


CONTACT_RE = re.compile(
    r"^\s*([A-Z0-9]{3})\s+(-?\d+)\s+(\S)\s+(-?\d+)\s+"
    r"([A-Z0-9]{3})\s+(-?\d+)\s+(\S)\s+(-?\d+)\s+"
    r"(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+"
    r"(-?\d+(?:\.\d+)?)\s*$"
)

BURIAL_RE = re.compile(
    r"^\s*([A-Z0-9]{3})\s+(-?\d+)\s+(\S)\s+(-?\d+)\s+(-?\d+(?:\.\d+)?)\s*$"
)

PAIR_RE = re.compile(
    r"^\s*(\d+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(\d+)\s*$"
)


HYDROPHOBIC = {"ALA", "VAL", "LEU", "ILE", "MET", "PRO"}
AROMATIC = {"PHE", "TYR", "TRP", "HIS"}
POSITIVE = {"LYS", "ARG", "HIS"}
NEGATIVE = {"ASP", "GLU"}
POLAR = {"SER", "THR", "ASN", "GLN", "CYS"}
HBOND_CAPABLE = POLAR | AROMATIC | POSITIVE | NEGATIVE


def residue_chemistry(res):
    if res in HYDROPHOBIC:
        return "hydrophobic"
    if res in POSITIVE:
        return "positive"
    if res in NEGATIVE:
        return "negative"
    if res in POLAR:
        return "polar"
    if res in AROMATIC:
        return "aromatic"
    return "other"


def classify_interaction(res1, res2, distance):
    if (res1 in POSITIVE and res2 in NEGATIVE) or (res1 in NEGATIVE and res2 in POSITIVE):
        return "electrostatic"
    if res1 in AROMATIC and res2 in AROMATIC:
        return "aromatic"
    if res1 in HYDROPHOBIC and res2 in HYDROPHOBIC:
        return "hydrophobic"
    if distance <= 3.5 and res1 in HBOND_CAPABLE and res2 in HBOND_CAPABLE:
        return "hydrogen_bond"
    return "other"


def residue_node(res, num, chain, ncs):
    return f"{res}{num}_{chain}_ncs{ncs}"


def parse_contacts_file(path):
    contacts, buried, au_pairs = [], [], []
    section = None

    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.rstrip("\n")

            if line.startswith("  Atoms"):
                section = "au_pairs"
                continue
            if line.startswith("Residue contacts"):
                section = "contacts"
                continue
            if line.startswith("Residue buried areas"):
                section = "buried"
                continue
            if not line.strip() or line.lstrip().startswith("residue"):
                continue

            if section == "au_pairs":
                m = PAIR_RE.match(line)
                if m:
                    au_pairs.append({
                        "line": line_number,
                        "atoms": int(m.group(1)),
                        "mtrix": int(m.group(2)),
                        "smtry": int(m.group(3)),
                        "cell_x": int(m.group(4)),
                        "cell_y": int(m.group(5)),
                        "cell_z": int(m.group(6)),
                        "mtrix_ref": int(m.group(7)),
                        "copies": int(m.group(8)),
                    })

            elif section == "contacts":
                m = CONTACT_RE.match(line)
                if m:
                    contacts.append({
                        "line": line_number,
                        "res1": m.group(1),
                        "num1": int(m.group(2)),
                        "chain1": m.group(3),
                        "ncs1": int(m.group(4)),
                        "res2": m.group(5),
                        "num2": int(m.group(6)),
                        "chain2": m.group(7),
                        "ncs2": int(m.group(8)),
                        "sym2": int(m.group(9)),
                        "cell_x": int(m.group(10)),
                        "cell_y": int(m.group(11)),
                        "cell_z": int(m.group(12)),
                        "distance": float(m.group(13)),
                    })

            elif section == "buried":
                m = BURIAL_RE.match(line)
                if m:
                    buried.append({
                        "line": line_number,
                        "res": m.group(1),
                        "num": int(m.group(2)),
                        "chain": m.group(3),
                        "ncs": int(m.group(4)),
                        "buried_area": float(m.group(5)),
                    })

    contacts_df = pd.DataFrame(contacts)
    buried_df = pd.DataFrame(buried)
    au_pairs_df = pd.DataFrame(au_pairs)

    if contacts_df.empty:
        raise ValueError("No contacts parsed. Check the input file.")

    contacts_df["node1"] = contacts_df.apply(
        lambda r: residue_node(r.res1, r.num1, r.chain1, r.ncs1), axis=1
    )
    contacts_df["node2"] = contacts_df.apply(
        lambda r: residue_node(r.res2, r.num2, r.chain2, r.ncs2), axis=1
    )
    contacts_df["node_pair"] = contacts_df.apply(
        lambda r: tuple(sorted([r.node1, r.node2])), axis=1
    )
    contacts_df["chain_pair_undirected"] = contacts_df.apply(
        lambda r: "-".join(sorted([r.chain1, r.chain2])), axis=1
    )
    contacts_df["interaction_type"] = contacts_df.apply(
        lambda r: classify_interaction(r.res1, r.res2, r.distance), axis=1
    )

    unique_df = contacts_df.drop_duplicates("node_pair").copy()
    return contacts_df, unique_df, buried_df, au_pairs_df


def filter_contacts(df, min_distance):
    before = len(df)
    filtered = df[df["distance"] >= min_distance].copy()
    return filtered, before - len(filtered)


def chain_interaction_tables(df):
    matrix = pd.crosstab(df["chain1"], df["chain2"])

    directed = (
        df.groupby(["chain1", "chain2"])
        .agg(
            contacts=("distance", "count"),
            mean_distance=("distance", "mean"),
            min_distance=("distance", "min"),
        )
        .reset_index()
        .sort_values("contacts", ascending=False)
    )

    return directed, matrix


def residue_frequencies(df):
    all_res = pd.concat([
        df[["res1"]].rename(columns={"res1": "residue"}),
        df[["res2"]].rename(columns={"res2": "residue"})
    ])

    return (
        all_res.value_counts("residue")
        .rename_axis("residue")
        .reset_index(name="count")
        .sort_values("count", ascending=False)
    )


def interaction_type_distribution(df):
    wanted = ["hydrogen_bond", "electrostatic", "hydrophobic", "aromatic"]

    table = (
        df[df["interaction_type"].isin(wanted)]
        .value_counts("interaction_type")
        .rename_axis("interaction_type")
        .reset_index(name="count")
    )

    for category in wanted:
        if category not in set(table["interaction_type"]):
            table.loc[len(table)] = [category, 0]

    table["interaction_type"] = pd.Categorical(
        table["interaction_type"],
        categories=wanted,
        ordered=True
    )

    return table.sort_values("interaction_type")


def distance_statistics(df):
    stats = df["distance"].describe().to_frame("value")
    stats.loc["contacts_<=3A"] = (df["distance"] <= 3.0).sum()
    stats.loc["contacts_<=4A"] = (df["distance"] <= 4.0).sum()
    stats.loc["contacts_<=5A"] = (df["distance"] <= 5.0).sum()
    stats.loc["fraction_<=3A"] = (df["distance"] <= 3.0).mean()
    stats.loc["fraction_<=4A"] = (df["distance"] <= 4.0).mean()
    return stats


def prepare_buried_area_tables(buried_df):
    if buried_df.empty:
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

    buried = buried_df.copy()
    buried["chemistry_class"] = buried["res"].map(residue_chemistry)

    by_residue_type = (
        buried.groupby("res", as_index=False)
        .agg(
            total_buried_area=("buried_area", "sum"),
            mean_buried_area=("buried_area", "mean"),
            residue_count=("buried_area", "count"),
        )
        .sort_values("total_buried_area", ascending=False)
    )

    by_chain = (
        buried.groupby("chain", as_index=False)
        .agg(
            total_buried_area=("buried_area", "sum"),
            mean_buried_area=("buried_area", "mean"),
            residue_count=("buried_area", "count"),
        )
        .sort_values("total_buried_area", ascending=False)
    )

    by_chemistry = (
        buried.groupby("chemistry_class", as_index=False)
        .agg(
            total_buried_area=("buried_area", "sum"),
            mean_buried_area=("buried_area", "mean"),
            residue_count=("buried_area", "count"),
        )
        .sort_values("total_buried_area", ascending=False)
    )

    return by_residue_type, by_chain, by_chemistry


def save_table(df, outdir, name):
    path = outdir / f"{name}.csv"
    df.to_csv(path, index=False)
    return path


def plot_distance_distribution(df, outdir):
    plt.figure(figsize=(8, 5))
    df["distance"].hist(bins=30)
    plt.xlabel("Distance (Å)")
    plt.ylabel("Number of contacts")
    plt.title("Residue contact distance distribution")
    plt.tight_layout()
    plt.savefig(outdir / "distance_distribution_filtered.png", dpi=300)
    plt.close()


def plot_residue_frequency(freq, outdir):
    top = freq.head(15).sort_values("count")

    plt.figure(figsize=(8, 6))
    plt.barh(top["residue"], top["count"])
    plt.xlabel("Contact count")
    plt.ylabel("Residue type")
    plt.title("Top residue types in interfaces")
    plt.tight_layout()
    plt.savefig(outdir / "residue_frequency_top15_filtered.png", dpi=300)
    plt.close()


def plot_chain_matrix(chain_matrix, outdir):
    plt.figure(figsize=(7, 6))
    plt.imshow(chain_matrix.values)
    plt.xticks(range(len(chain_matrix.columns)), chain_matrix.columns)
    plt.yticks(range(len(chain_matrix.index)), chain_matrix.index)
    plt.xlabel("Chain 2")
    plt.ylabel("Chain 1")
    plt.title("Chain interaction matrix")
    plt.colorbar(label="Contacts")
    plt.tight_layout()
    plt.savefig(outdir / "chain_interaction_matrix_filtered.png", dpi=300)
    plt.close()


def plot_interaction_types(interaction_table, outdir):
    plt.figure(figsize=(8, 5))
    plt.bar(interaction_table["interaction_type"], interaction_table["count"])
    plt.xlabel("Interaction type")
    plt.ylabel("Contact count")
    plt.title("Distribution of interface interaction types")
    plt.xticks(rotation=25, ha="right")
    plt.tight_layout()
    plt.savefig(outdir / "interaction_type_distribution.png", dpi=300)
    plt.close()


def plot_buried_by_residue_type(table, outdir):
    if table.empty:
        return

    top = table.head(15).sort_values("total_buried_area")

    plt.figure(figsize=(8, 6))
    plt.barh(top["res"], top["total_buried_area"])
    plt.xlabel("Total buried SASA")
    plt.ylabel("Residue type")
    plt.title("Buried area by residue type")
    plt.tight_layout()
    plt.savefig(outdir / "buried_area_by_residue_type.png", dpi=300)
    plt.close()


def plot_buried_by_chain(table, outdir):
    if table.empty:
        return

    plt.figure(figsize=(7, 5))
    plt.bar(table["chain"], table["total_buried_area"])
    plt.xlabel("Chain")
    plt.ylabel("Total buried SASA")
    plt.title("Buried area by chain")
    plt.tight_layout()
    plt.savefig(outdir / "buried_area_by_chain.png", dpi=300)
    plt.close()


def plot_buried_by_chemistry(table, outdir):
    if table.empty:
        return

    plt.figure(figsize=(8, 5))
    plt.bar(table["chemistry_class"], table["total_buried_area"])
    plt.xlabel("Residue chemistry class")
    plt.ylabel("Total buried SASA")
    plt.title("Buried area by chemistry class")
    plt.xticks(rotation=25, ha="right")
    plt.tight_layout()
    plt.savefig(outdir / "buried_area_by_chemistry_class.png", dpi=300)
    plt.close()


def write_text_summary(outdir, raw_df, raw_filtered, unique_filtered, removed_raw, removed_unique, dist_stats):
    summary_path = outdir / "summary.txt"

    with open(summary_path, "w", encoding="utf-8") as out:
        out.write("Viral capsid contact-analysis summary\n")
        out.write("=====================================\n\n")
        out.write(f"Raw contacts parsed before filtering: {len(raw_df)}\n")
        out.write(f"Raw contacts removed as < 1.0 Å artifacts/clashes: {removed_raw}\n")
        out.write(f"Raw contacts after filtering: {len(raw_filtered)}\n")
        out.write(f"Unique contacts removed as < 1.0 Å artifacts/clashes: {removed_unique}\n")
        out.write(f"Unique contacts used in analysis: {len(unique_filtered)}\n")
        out.write(f"Chains detected: {', '.join(sorted(set(raw_filtered.chain1) | set(raw_filtered.chain2)))}\n\n")

        out.write("Distance statistics after filtering:\n")
        out.write(dist_stats.to_string())
        out.write("\n\n")

        out.write("Generated figures:\n")
        out.write("- chain_interaction_matrix_filtered.png\n")
        out.write("- distance_distribution_filtered.png\n")
        out.write("- interaction_type_distribution.png\n")
        out.write("- residue_frequency_top15_filtered.png\n")
        out.write("- buried_area_by_residue_type.png\n")
        out.write("- buried_area_by_chain.png\n")
        out.write("- buried_area_by_chemistry_class.png\n")

    return summary_path


def main():
    parser = argparse.ArgumentParser(description="Analyze viral capsid contacts and buried SASA.")
    parser.add_argument("contacts_file", help="Example: 1b35_contacts.txt")
    parser.add_argument("--outdir", default="capsid_final_figures")
    parser.add_argument("--min-distance", type=float, default=1.0)
    parser.add_argument("--use-raw", action="store_true")
    args = parser.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    raw_df, unique_df, buried_df, au_pairs_df = parse_contacts_file(Path(args.contacts_file))

    raw_filtered, removed_raw = filter_contacts(raw_df, args.min_distance)
    unique_filtered, removed_unique = filter_contacts(unique_df, args.min_distance)

    analysis_df = raw_filtered if args.use_raw else unique_filtered

    directed_chain, chain_matrix = chain_interaction_tables(analysis_df)
    residue_freq = residue_frequencies(analysis_df)
    interaction_table = interaction_type_distribution(analysis_df)
    dist_stats = distance_statistics(analysis_df)

    buried_by_residue, buried_by_chain, buried_by_chemistry = prepare_buried_area_tables(buried_df)

    save_table(raw_filtered, outdir, "all_raw_contacts_filtered")
    save_table(unique_filtered, outdir, "unique_residue_contacts_filtered")
    save_table(buried_df, outdir, "buried_areas")
    save_table(directed_chain, outdir, "chain_interactions_directed")
    chain_matrix.to_csv(outdir / "chain_interaction_matrix.csv")
    save_table(residue_freq, outdir, "residue_contact_frequency")
    save_table(interaction_table, outdir, "interaction_type_distribution")
    save_table(buried_by_residue, outdir, "buried_area_by_residue_type")
    save_table(buried_by_chain, outdir, "buried_area_by_chain")
    save_table(buried_by_chemistry, outdir, "buried_area_by_chemistry_class")
    dist_stats.to_csv(outdir / "distance_statistics.csv")

    plot_chain_matrix(chain_matrix, outdir)
    plot_distance_distribution(analysis_df, outdir)
    plot_interaction_types(interaction_table, outdir)
    plot_residue_frequency(residue_freq, outdir)
    plot_buried_by_residue_type(buried_by_residue, outdir)
    plot_buried_by_chain(buried_by_chain, outdir)
    plot_buried_by_chemistry(buried_by_chemistry, outdir)

    summary_path = write_text_summary(
        outdir,
        raw_df,
        raw_filtered,
        unique_filtered,
        removed_raw,
        removed_unique,
        dist_stats,
    )

    print("\nAnalysis complete.")
    print(f"Removed raw contacts below {args.min_distance} Å: {removed_raw}")
    print(f"Removed unique contacts below {args.min_distance} Å: {removed_unique}")
    print(f"Contacts used in analysis: {len(analysis_df)}")
    print(f"Output folder: {outdir.resolve()}")
    print(f"Summary file: {summary_path.resolve()}")


if __name__ == "__main__":
    main()