#!/usr/bin/env python3

"""
Biological Ranking of Threonine Mutation Targets in Viral Capsid Interfaces

This script identifies and ranks biologically relevant threonine (THR)
residues as candidates for site-directed mutagenesis using residue contact
and buried surface area information generated by ChimeraX crystalcontacts.

The script first parses residue contact and buried SASA data, then corrects
symmetry-expanded residue numbering by converting observed residue numbers
(e.g., 2124) back to their original sequence numbering (e.g., residue 124),
allowing all symmetry copies of the same residue to be analyzed together.

For every threonine residue, the script evaluates:
- Total number of residue contacts
- Inter-chain and inter-copy interactions
- Symmetry-related contacts
- Hydrogen bond-like interactions
- Contact geometry
- Partner residue diversity
- Buried solvent-accessible surface area (SASA)

These structural features are combined into a biologically weighted scoring
system that prioritizes residues making substantial contributions to
biological interfaces while reducing the influence of peripheral crystal
packing contacts.

Each threonine residue is then classified according to its biological
importance, ranked, and assigned recommended mutation strategies
(T→A as the primary mutation, with T→V and T→S as control mutations).

The script generates:
- Normalized contact and buried area datasets.
- Detailed contact information for every threonine residue.
- A ranked list of candidate mutation sites.
- A recommendation report describing the highest-priority biological
  mutation targets and the rationale behind their selection.

This workflow was developed to identify the most biologically meaningful
interface residues for experimental mutagenesis and subsequent investigation
of viral capsid stability and assembly.

"""

import argparse
import re
from pathlib import Path
import pandas as pd
import numpy as np

CONTACT_RE = re.compile(
    r"^\s*([A-Z0-9]{3})\s+(-?\d+)\s+(\S)\s+(-?\d+)\s+"
    r"([A-Z0-9]{3})\s+(-?\d+)\s+(\S)\s+(-?\d+)\s+"
    r"(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+"
    r"(-?\d+(?:\.\d+)?)\s*$"
)

BURIAL_RE = re.compile(
    r"^\s*([A-Z0-9]{3})\s+(-?\d+)\s+(\S)\s+(-?\d+)\s+(-?\d+(?:\.\d+)?)\s*$"
)

HYDROPHOBIC = {"ALA", "VAL", "LEU", "ILE", "MET", "PRO", "PHE", "TRP"}
AROMATIC = {"PHE", "TYR", "TRP", "HIS"}
POSITIVE = {"LYS", "ARG", "HIS"}
NEGATIVE = {"ASP", "GLU"}
POLAR = {"SER", "THR", "ASN", "GLN", "CYS", "TYR"}
HBOND_CAPABLE = POLAR | POSITIVE | NEGATIVE | {"HIS"}


def normalize_residue_number(num: int, modulus: int = 1000) -> tuple[int, int]:
    """
    Convert ChimeraX symmetry-expanded residue numbering to sequence numbering.

    Examples:
      2124 -> sequence residue 124, copy_prefix 2
      3159 -> sequence residue 159, copy_prefix 3
      120  -> sequence residue 120, copy_prefix 0

    If your real protein has residue numbers >1000, run with --no-normalize.
    """
    sign = -1 if num < 0 else 1
    abs_num = abs(num)
    if abs_num >= modulus:
        seq = abs_num % modulus
        copy_prefix = abs_num // modulus
        if seq == 0:
            seq = modulus
            copy_prefix -= 1
        return sign * seq, copy_prefix
    return num, 0


def residue_node(res, observed_num, chain, ncs):
    return f"{res}{observed_num}_chain{chain}_ncs{ncs}"


def classify_interaction(res1, res2, distance):
    if (res1 in POSITIVE and res2 in NEGATIVE) or (res1 in NEGATIVE and res2 in POSITIVE):
        return "electrostatic"
    if res1 in AROMATIC and res2 in AROMATIC:
        return "aromatic"
    if res1 in HYDROPHOBIC and res2 in HYDROPHOBIC:
        return "hydrophobic"
    if distance <= 3.5 and res1 in HBOND_CAPABLE and res2 in HBOND_CAPABLE:
        return "hydrogen_bond_like"
    return "other"


def minmax(series):
    series = pd.Series(series, dtype=float)
    if series.empty or series.max() == series.min():
        return pd.Series(np.zeros(len(series)), index=series.index)
    return (series - series.min()) / (series.max() - series.min())


def parse_chimerax_contacts(path: Path, normalize: bool = True, modulus: int = 1000):
    contacts, buried = [], []
    section = None

    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.rstrip("\n")

            if line.startswith("Residue contacts"):
                section = "contacts"
                continue
            if line.startswith("Residue buried areas"):
                section = "buried"
                continue
            if line.startswith("  Atoms"):
                section = "au_pairs"
                continue
            if not line.strip() or line.lstrip().startswith("residue"):
                continue

            if section == "contacts":
                m = CONTACT_RE.match(line)
                if not m:
                    continue

                num1 = int(m.group(2))
                num2 = int(m.group(6))
                seq1, copy1 = normalize_residue_number(num1, modulus) if normalize else (num1, 0)
                seq2, copy2 = normalize_residue_number(num2, modulus) if normalize else (num2, 0)

                res1, chain1, ncs1 = m.group(1), m.group(3), int(m.group(4))
                res2, chain2, ncs2 = m.group(5), m.group(7), int(m.group(8))
                sym2 = int(m.group(9))
                cell_x, cell_y, cell_z = int(m.group(10)), int(m.group(11)), int(m.group(12))
                distance = float(m.group(13))

                contacts.append({
                    "line": line_number,
                    "res1": res1,
                    "observed_num1": num1,
                    "sequence_num1": seq1,
                    "copy_prefix1": copy1,
                    "chain1": chain1,
                    "ncs1": ncs1,
                    "res2": res2,
                    "observed_num2": num2,
                    "sequence_num2": seq2,
                    "copy_prefix2": copy2,
                    "chain2": chain2,
                    "ncs2": ncs2,
                    "sym2": sym2,
                    "cell_x": cell_x,
                    "cell_y": cell_y,
                    "cell_z": cell_z,
                    "distance": distance,
                    "interaction_type": classify_interaction(res1, res2, distance),
                })

            elif section == "buried":
                m = BURIAL_RE.match(line)
                if not m:
                    continue

                num = int(m.group(2))
                seq, copy = normalize_residue_number(num, modulus) if normalize else (num, 0)

                buried.append({
                    "line": line_number,
                    "res": m.group(1),
                    "observed_num": num,
                    "sequence_num": seq,
                    "copy_prefix": copy,
                    "chain": m.group(3),
                    "ncs": int(m.group(4)),
                    "buried_area": float(m.group(5)),
                })

    contacts_df = pd.DataFrame(contacts)
    buried_df = pd.DataFrame(buried)

    if contacts_df.empty:
        raise ValueError("No residue contacts parsed. Check that this is ChimeraX crystalcontacts output.")

    contacts_df["node1"] = contacts_df.apply(
        lambda r: residue_node(r.res1, r.observed_num1, r.chain1, r.ncs1), axis=1
    )
    contacts_df["node2"] = contacts_df.apply(
        lambda r: residue_node(r.res2, r.observed_num2, r.chain2, r.ncs2), axis=1
    )
    contacts_df["node_pair"] = contacts_df.apply(
        lambda r: tuple(sorted([r.node1, r.node2])), axis=1
    )
    contacts_df = contacts_df.drop_duplicates("node_pair").copy()

    return contacts_df, buried_df


def extract_thr_contact_rows(contacts_df: pd.DataFrame):
    rows = []

    for _, r in contacts_df.iterrows():
        # THR as residue 1
        if r.res1 == "THR":
            rows.append({
                "line": r.line,
                "target_observed_num": r.observed_num1,
                "target_sequence_num": r.sequence_num1,
                "target_copy_prefix": r.copy_prefix1,
                "target_chain": r.chain1,
                "target_ncs": r.ncs1,
                "partner_res": r.res2,
                "partner_observed_num": r.observed_num2,
                "partner_sequence_num": r.sequence_num2,
                "partner_copy_prefix": r.copy_prefix2,
                "partner_chain": r.chain2,
                "partner_ncs": r.ncs2,
                "sym2": r.sym2,
                "cell_x": r.cell_x,
                "cell_y": r.cell_y,
                "cell_z": r.cell_z,
                "distance": r.distance,
                "interaction_type": r.interaction_type,
                "target_side": "res1",
            })

        # THR as residue 2
        if r.res2 == "THR":
            rows.append({
                "line": r.line,
                "target_observed_num": r.observed_num2,
                "target_sequence_num": r.sequence_num2,
                "target_copy_prefix": r.copy_prefix2,
                "target_chain": r.chain2,
                "target_ncs": r.ncs2,
                "partner_res": r.res1,
                "partner_observed_num": r.observed_num1,
                "partner_sequence_num": r.sequence_num1,
                "partner_copy_prefix": r.copy_prefix1,
                "partner_chain": r.chain1,
                "partner_ncs": r.ncs1,
                "sym2": r.sym2,
                "cell_x": r.cell_x,
                "cell_y": r.cell_y,
                "cell_z": r.cell_z,
                "distance": r.distance,
                "interaction_type": r.interaction_type,
                "target_side": "res2",
            })

    thr = pd.DataFrame(rows)
    if thr.empty:
        return thr

    thr["inter_chain_or_copy"] = (
        (thr["target_chain"].astype(str) != thr["partner_chain"].astype(str)) |
        (thr["target_copy_prefix"].astype(int) != thr["partner_copy_prefix"].astype(int)) |
        (thr["target_ncs"].astype(int) != thr["partner_ncs"].astype(int))
    )
    thr["symmetry_related"] = (
        (thr["sym2"].astype(int) != 0) |
        (thr["cell_x"].astype(int) != 0) |
        (thr["cell_y"].astype(int) != 0) |
        (thr["cell_z"].astype(int) != 0) |
        (thr["target_copy_prefix"].astype(int) != thr["partner_copy_prefix"].astype(int))
    )
    thr["hbond_like"] = (
        (thr["distance"] <= 3.5) &
        (thr["partner_res"].isin(HBOND_CAPABLE))
    )
    thr["good_geometry"] = thr["distance"].between(2.6, 4.0)

    thr["mutation_site"] = "T" + thr["target_sequence_num"].astype(str)
    thr["observed_site"] = "T" + thr["target_observed_num"].astype(str)

    return thr


def rank_thr_sites(thr_contacts: pd.DataFrame, buried_df: pd.DataFrame):
    if thr_contacts.empty:
        return pd.DataFrame()

    thr_buried = buried_df[buried_df["res"] == "THR"].copy()
    if thr_buried.empty:
        burial_by_site = pd.DataFrame(columns=[
            "target_sequence_num", "sum_buried_sasa", "max_buried_sasa",
            "mean_buried_sasa", "observed_thr_instances"
        ])
    else:
        burial_by_site = (
            thr_buried.groupby("sequence_num", as_index=False)
            .agg(
                sum_buried_sasa=("buried_area", "sum"),
                max_buried_sasa=("buried_area", "max"),
                mean_buried_sasa=("buried_area", "mean"),
                observed_thr_instances=("buried_area", "count"),
            )
            .rename(columns={"sequence_num": "target_sequence_num"})
        )

    # Aggregate at sequence residue number level because this is the actual mutation site.
    grouped = (
        thr_contacts.groupby("target_sequence_num", as_index=False)
        .agg(
            total_contacts=("distance", "count"),
            inter_chain_or_copy_contacts=("inter_chain_or_copy", "sum"),
            symmetry_related_contacts=("symmetry_related", "sum"),
            hbond_like_contacts=("hbond_like", "sum"),
            good_geometry_contacts=("good_geometry", "sum"),
            unique_partner_residue_numbers=("partner_sequence_num", "nunique"),
            unique_partner_residue_types=("partner_res", "nunique"),
            unique_partner_chains=("partner_chain", "nunique"),
            min_distance=("distance", "min"),
            mean_distance=("distance", "mean"),
            observed_numbers=("target_observed_num", lambda x: ",".join(map(str, sorted(set(x))))),
            observed_chains=("target_chain", lambda x: ",".join(map(str, sorted(set(x.astype(str)))))),
            observed_copy_prefixes=("target_copy_prefix", lambda x: ",".join(map(str, sorted(set(x))))),
            observed_ncs=("target_ncs", lambda x: ",".join(map(str, sorted(set(x))))),
        )
    )

    ranked = grouped.merge(burial_by_site, on="target_sequence_num", how="left")
    for col in ["sum_buried_sasa", "max_buried_sasa", "mean_buried_sasa", "observed_thr_instances"]:
        ranked[col] = ranked[col].fillna(0)

    # Normalized, biologically weighted score:
    # buried interface contribution is deliberately strong, so peripheral crystal contacts
    # do not dominate only because they have many symmetry records.
    ranked["score_burial_sum"] = minmax(ranked["sum_buried_sasa"])
    ranked["score_burial_max"] = minmax(ranked["max_buried_sasa"])
    ranked["score_contacts"] = minmax(ranked["total_contacts"])
    ranked["score_inter"] = minmax(ranked["inter_chain_or_copy_contacts"])
    ranked["score_symmetry"] = minmax(ranked["symmetry_related_contacts"])
    ranked["score_hbond"] = minmax(ranked["hbond_like_contacts"])
    ranked["score_geometry"] = minmax(ranked["good_geometry_contacts"])
    ranked["score_partner_diversity"] = minmax(
        ranked["unique_partner_residue_numbers"] + ranked["unique_partner_chains"]
    )
    # Shorter contacts are better, but avoid rewarding clashes below 2.4 A.
    ranked["score_distance"] = 1 - minmax(ranked["mean_distance"])
    ranked.loc[ranked["min_distance"] < 2.4, "score_distance"] *= 0.5

    ranked["biological_score"] = (
        0.25 * ranked["score_burial_sum"] +
        0.20 * ranked["score_burial_max"] +
        0.15 * ranked["score_inter"] +
        0.10 * ranked["score_contacts"] +
        0.10 * ranked["score_symmetry"] +
        0.08 * ranked["score_hbond"] +
        0.05 * ranked["score_geometry"] +
        0.04 * ranked["score_partner_diversity"] +
        0.03 * ranked["score_distance"]
    )

    ranked["very_low_burial_flag"] = ranked["max_buried_sasa"] < 2.0

    def classify(row):
        if row["max_buried_sasa"] >= 10 and row["inter_chain_or_copy_contacts"] >= 2:
            return "primary_biological_interface_candidate"
        if row["max_buried_sasa"] >= 5 and row["inter_chain_or_copy_contacts"] >= 2:
            return "good_biological_interface_candidate"
        if row["symmetry_related_contacts"] >= 5 and row["max_buried_sasa"] < 5:
            return "symmetry_hotspot_but_peripheral"
        return "lower_priority"

    ranked["candidate_class"] = ranked.apply(classify, axis=1)
    ranked["recommended_mutation_primary"] = "T" + ranked["target_sequence_num"].astype(str) + "A"
    ranked["recommended_mutation_controls"] = (
        "T" + ranked["target_sequence_num"].astype(str) + "V / " +
        "T" + ranked["target_sequence_num"].astype(str) + "S"
    )

    cols = [
        "target_sequence_num",
        "recommended_mutation_primary",
        "biological_score",
        "candidate_class",
        "sum_buried_sasa",
        "max_buried_sasa",
        "mean_buried_sasa",
        "total_contacts",
        "inter_chain_or_copy_contacts",
        "symmetry_related_contacts",
        "hbond_like_contacts",
        "good_geometry_contacts",
        "unique_partner_residue_numbers",
        "unique_partner_residue_types",
        "unique_partner_chains",
        "min_distance",
        "mean_distance",
        "observed_numbers",
        "observed_chains",
        "observed_copy_prefixes",
        "observed_ncs",
        "observed_thr_instances",
        "very_low_burial_flag",
        "recommended_mutation_controls",
    ]
    return ranked.sort_values("biological_score", ascending=False)[cols]


def write_recommendations(outdir: Path, ranked: pd.DataFrame, normalize: bool):
    path = outdir / "biological_threonine_recommendations.txt"

    with open(path, "w", encoding="utf-8") as f:
        f.write("Biologically weighted THR mutation target recommendations\n")
        f.write("========================================================\n\n")
        f.write("Important numbering note:\n")
        if normalize:
            f.write(
                "Residue numbers were normalized for ChimeraX symmetry-expanded numbering.\n"
                "For example, observed THR 2124 is reported as sequence mutation T124,\n"
                "because it likely represents copy-prefix 2 + residue 124.\n\n"
            )
        else:
            f.write("Residue numbers were NOT normalized because --no-normalize was used.\n\n")

        f.write("Selection logic:\n")
        f.write(
            "Targets are ranked at the sequence-residue level, not at the individual\n"
            "symmetry-copy level. The score prioritizes buried interface contribution,\n"
            "inter-chain/copy contacts, symmetry contacts, hydrogen-bond-like contacts,\n"
            "partner diversity, and reasonable contact geometry. Low-burial symmetry-only\n"
            "contacts are kept as secondary/peripheral candidates rather than automatically\n"
            "selected as the best biological target.\n\n"
        )

        if ranked.empty:
            f.write("No THR targets found.\n")
            return path

        top = ranked.iloc[0]
        f.write("Best biological mutation target:\n")
        f.write(f"- mutation: {top.recommended_mutation_primary}\n")
        f.write(f"- sequence residue: THR {int(top.target_sequence_num)}\n")
        f.write(f"- observed ChimeraX residue numbers: {top.observed_numbers}\n")
        f.write(f"- observed chains: {top.observed_chains}\n")
        f.write(f"- biological_score: {top.biological_score:.3f}\n")
        f.write(f"- candidate_class: {top.candidate_class}\n")
        f.write(f"- sum_buried_sasa: {top.sum_buried_sasa:.2f}\n")
        f.write(f"- max_buried_sasa: {top.max_buried_sasa:.2f}\n")
        f.write(f"- total_contacts: {int(top.total_contacts)}\n")
        f.write(f"- inter_chain_or_copy_contacts: {int(top.inter_chain_or_copy_contacts)}\n")
        f.write(f"- symmetry_related_contacts: {int(top.symmetry_related_contacts)}\n")
        f.write(f"- hbond_like_contacts: {int(top.hbond_like_contacts)}\n\n")

        peripheral = ranked[ranked["candidate_class"].eq("symmetry_hotspot_but_peripheral")]
        if not peripheral.empty:
            sec = peripheral.iloc[0]
        elif len(ranked) > 1:
            sec = ranked.iloc[1]
        else:
            sec = None

        if sec is not None:
            f.write("Secondary/comparison target:\n")
            f.write(f"- mutation: {sec.recommended_mutation_primary}\n")
            f.write(f"- sequence residue: THR {int(sec.target_sequence_num)}\n")
            f.write(f"- observed ChimeraX residue numbers: {sec.observed_numbers}\n")
            f.write(f"- observed chains: {sec.observed_chains}\n")
            f.write(f"- candidate_class: {sec.candidate_class}\n")
            f.write(f"- max_buried_sasa: {sec.max_buried_sasa:.2f}\n")
            f.write(f"- total_contacts: {int(sec.total_contacts)}\n")
            f.write(f"- symmetry_related_contacts: {int(sec.symmetry_related_contacts)}\n\n")

        f.write("Recommended mutation design:\n")
        f.write("- T->A: first disruptive mutation; removes the hydroxyl group.\n")
        f.write("- T->V: structural control; similar beta-branched shape but no hydroxyl.\n")
        f.write("- T->S: conservative control; keeps hydroxyl but changes side-chain size.\n")

    return path


def main():
    parser = argparse.ArgumentParser(
        description="Rank biologically plausible THR mutation targets from ChimeraX crystalcontacts output."
    )
    parser.add_argument("contacts_file", help="ChimeraX crystalcontacts text file, e.g. 1bmv_contacts.txt")
    parser.add_argument("--outdir", default="thr_biological_targets_fixed")
    parser.add_argument("--min-distance", type=float, default=2.4, help="Remove likely clash/artifact contacts below this distance.")
    parser.add_argument("--modulus", type=int, default=1000, help="Numbering modulus for symmetry-expanded residues, default 1000.")
    parser.add_argument("--no-normalize", action="store_true", help="Do not convert 2124->124 etc.")
    args = parser.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    normalize = not args.no_normalize
    contacts_df, buried_df = parse_chimerax_contacts(Path(args.contacts_file), normalize=normalize, modulus=args.modulus)
    contacts_df = contacts_df[contacts_df["distance"] >= args.min_distance].copy()

    thr_contacts = extract_thr_contact_rows(contacts_df)
    ranked = rank_thr_sites(thr_contacts, buried_df)

    contacts_df.to_csv(outdir / "all_unique_contacts_normalized.csv", index=False)
    buried_df.to_csv(outdir / "buried_areas_normalized.csv", index=False)
    thr_contacts.to_csv(outdir / "threonine_contact_details_normalized.csv", index=False)
    ranked.to_csv(outdir / "biological_threonine_targets_ranked_fixed.csv", index=False)
    rec_path = write_recommendations(outdir, ranked, normalize=normalize)

    print("\nAnalysis complete.")
    print(f"Contacts used after filtering: {len(contacts_df)}")
    print(f"THR contact rows: {len(thr_contacts)}")
    print(f"Ranked THR mutation sites: {len(ranked)}")
    if not ranked.empty:
        top = ranked.iloc[0]
        print(f"Best target: {top.recommended_mutation_primary} (sequence THR {int(top.target_sequence_num)})")
        print(f"Observed ChimeraX residue number(s): {top.observed_numbers}")
        print(f"Biological score: {top.biological_score:.3f}")
    print(f"Output folder: {outdir.resolve()}")
    print(f"Recommendations: {rec_path.resolve()}")


if __name__ == "__main__":
    main()
